name: base

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - numpy
  - xarray
  - pandas
  - cartopy
  - matplotlib 
  - seaborn
  - geopy
  - basemap
  - netcdf4
  - cis
  - bokeh
  - metpy
  - scipy
  - scikit-learn
  - nc-time-axis
  - PyTables
  - xlrd
  - plotly
  - ipyleaflet
  - rasterio
  - tqdm
  - requests
  - pillow
  - branca
  - geopandas
  - voila
  - nodejs
  - pythreejs
  - bqplot
  - cdsapi 
  - folium
  - basemap-data-hires
  - plotly
  - rasterstats
  - cfgrib
  - cdo
  - nco
  - jupytext
  - pydap
  - papermill
  - geonum
  - pip:
      - dask_labextension
      - ipydatawidgets
      - sidecar
      - geojsoncontour
      - nbgitpuller
      - pysplit
